### ISSUE TITLE
Provide a base class for CompilerPasses that automate common workflows

### ISSUE THREAD

**Issue by keichinger** [Becklyn/RadBundle#16]
Just like our custom `Bundle`, `BundleConfiguration` and `BundleExtension` it'd enhance productivity and reduce code duplication if we can provide a common `CompilerPass` class that does something along the line like this:

``` php
class RandomCompilerPass implements CompilerPassInterface
{
    /**
     * @inheritdoc
     */
    public function process (ContainerBuilder $container)
    {
        // collect all registered AppSettingsProviders
        $this->collectTagsAndAddToService($container, "service.tag", "service.collection.something", "collectMethodName");
    }


    /**
     * Collects the services with a given tag (and id) and adds them to a collection
     *
     * @param ContainerBuilder $container
     * @param string           $tag
     * @param string           $collectionTag
     * @param string           $collectionMethod
     */
    private function collectTagsAndAddToService (ContainerBuilder $container, $tag, $collectionTag, $collectionMethod)
    {
        $taggedServices = $container->findTaggedServiceIds($tag);
        $handlerCollectionDefinition = $container->getDefinition($collectionTag);

        foreach ($taggedServices as $serviceId => $tags)
        {
            $handlerCollectionDefinition->addMethodCall($collectionMethod, [new Reference($serviceId)]);
        }
    }
}
```

In every Compiler Pass we're duplicating the logic to collect and register tagged services with another service. 

Personally I'd at least provide two implementations for the `collectTagsAndAddToService` method. One as the example above and one for the cases where we want to collect services that may have multiple tags. One example for that can be seen at http://symfony.com/doc/current/service_container/tags.html#adding-additional-attributes-on-tags

**Comment by apfelbox** [comment]
You could add this with a single method, with the last argument being a callback, that receives the service definition and tag data.

**Comment by cH40z-Lord** [comment]
Would work as well, yeah, however I'm not so entirely sure how much we've saved then since we'd have to call the methods manually instead of letting the RadBundle do it for us.

I'm thinking about some arbitrary mapping like this

```php
[
    "service.tag" => ["service.collection", "registerTaggedService"],
    "another_service.tag" => ["another_service.collection", "registerSomeAwesomeService"],
    "manual.tagging" => [function (ContainerBuilder $container, $serviceId, $serviceTags) { /** do some manual work with the tagged service */ }],
]
```

which is returned by a getter, which would be the only thing that you'd have to implement for the entire `CompilerPass`. Still trivial to implement, both from our side (the implementors) and the using developers, and yet flexible enough to do whatever you want.

Ultimately you could still roll your own `process` method and call a `protected` base method if you want.

**Comment by apfelbox** [comment]
As we discussed before, I would go this way:

Add an array, that list all additional tag attributes in the correct order, example:

```php
$this->collectTagsAndAddToService($container, "some.tag", "my.service.id", "addHandler", ["key", "method"])
```

will add a call to:

```php
$myServiceId->addHandler($reference, $tags["key"] ?? null, $tags["method"] ?? null);
```

where `$reference` is the service with the tag.

This way you can configure it easily, and also support optional tag attributes.

Thoughts?

**Comment by cH40z-Lord** [comment]
Could you provide an example `services.yml` to illustrate your idea a bit further? I can't wrap my head around the 2nd and 3rd method parameter for `addHandler` right now and how `key` and `method` would work in your example.

**Comment by apfelbox** [comment]
The collection call of

```php
$this->collectTagsAndAddToService($container, "my.tag", "tag.collection", "addHandler", ["key", "method"]);
```

with this example `services.yml`:

```yml
services:
    service1:
        class: ...
        tags:
            - { name: my.tag, key: "abc", method: "someFunc" }

    service2:
        class: ...
        tags:
            - { name: my.tag, key: "123", method: "otherFunc" }

    service3:
        class: ...
        tags:
            - { name: my.tag, method: "myFunc" }

    service4:
        class: ...
        tags:
            - { name: my.tag, key: "xyz" }
```


would add the following calls in the container:


```php
$collection = $container->get("tag.collection");

collection->addHandler($container->get("service1"), "abc", "someFunc");
collection->addHandler($container->get("service2"), "123", "otherFunc");
collection->addHandler($container->get("service3"), null, "myFunc");
collection->addHandler($container->get("service4"), "xyz", null);
```

(this is pseudo code to make it more readable)


This way we can support tag attributes quite simply. You even get validation if you add typehints / do the checks in the `addHandler` method in your `tag.collection`-Service:


```php
public function addHandler (ServiceInterface $service, string $key = null, string $method)
{
    // ...
}
```

would properly fail for `service4`.

**Comment by cH40z-Lord** [comment]
Yeah, I like the simple idea of your proposal.

Let's do it.

![](https://media.giphy.com/media/yE3P1gj3qLMbe/giphy.gif)

**Comment by apfelbox** [comment]
Implementation proposal:

```php
private function collectTagsAndAddToService (ContainerBuilder $container, $tag, $collectionTag, $collectionMethod, array $tagAttributes = [])
{
    $taggedServices = $container->findTaggedServiceIds($tag);
    $handlerCollectionDefinition = $container->getDefinition($collectionTag);

    foreach ($taggedServices as $serviceId => $tags)
    {
        $parameters = array_map(
            function ($attr) use ($tags)
            {
                return $tags[$attr] ?? null;
            },
            $tagAttributes
        );

        // the service reference is the first parameter by convention
        array_unshift($parameters, new Reference($serviceId));

        $handlerCollectionDefinition->addMethodCall($collectionMethod, $parameters);
    }
}
```

If that looks ok, can you please prepare a PR and add some docs?

**Comment by apfelbox** [comment]
Implemented in core with `!tagged_locator` and `!tagged_iterator`
