### ISSUE TITLE
Delete + FlushEntity with Dependency-Chain

### ISSUE THREAD

**Issue by keichinger** [Becklyn/RadBundle#8]
Since we're encountering issues with entities that have relationships that make use of `casecade={"all"}` we need to manually flush entity dependencies either by checking types or creating specialized model classes, which are both not optimal.

This is the reason why we would like to use a more generalized implementation which may look like this

``` php
interface EntityDependenciesInterface
{
    function getDependencies();
}
```

`getDependencies();` can be implemented by any entity that has such dependencies and requires special treatment upon deletion. The method should return a list of properties which then can be used with the `PropertyAccessor` component to take care of that.

Keep in mind that we might also need to handle recursion as well.

**Comment by apfelbox** [comment]
This is now solved by just not flushing eagerly
